template/module/README.rst
template/module/static/description/index.html

Provide templates in rst and html format for module description to be displayed on Odoo Apps, an Odoo instance or Github (rst only).

[ADD] Description templates (rst, html)

---

.travis.yml

this Python version is really old.

drop testing with python2.6

---

template/module/README.rst

A simple way to visualy promote the endorsement of AGPL-3 by OCA

[IMP] Add AGPL-3 badge

---

template/module/README.rst

Remove extra spaces, show license in ALT text, don't separate contributors by blank line.

Better template

---

tools/clone_everything
tools/oca_projects.py

* use git fetch on already cloned repos
* try to use the github api to get an up to date list of repositories

Better clone everything

---

CONTRIBUTING.md

Seems to be the current convention used at Odoo SA's.
Fixes #87

Add guidelines for placing reports

---

CONTRIBUTING.md

Reverts OCA/maintainer-tools#90

Revert "Add guideline for version numbers"

---

Dockerfile-tx-bot
requirements.txt
setup.cfg
tools/config.py
tools/github_login.py
tools/tx_pull.py

Continuing with the work started by @samuellefever in #63, I have completed and improved the script to completely perform the task.
In my initial tests, it has taken 100 min to scan the current 23 OCA projects in Transifex. The problem is that Transifex doesn't have good mechanisms for checking the updates. In "Know issues" section of the script comments I go deep into possible solutions and details of this problem.
@max3903, @bwrsandman, @samuellefever please check.

Transifex -> GitHub synchronization script

---

template/module/__init__.py
template/module/__openerp__.py

Add missing files `__openerp__.py` and `__init__.py`.

Add template magic files. Required in all modules.

---

README.md

Please see message commit for further info.

[FIX] README

---

template/module/README.rst

add break line for quick edition in feedback hyperlink Fixes #138

[REF] add break line to feedback hyperlink

---

template/module/README.rst

Following https://github.com/OCA/server-tools/pull/261#discussion_r40427477

[REM] useless link https://www.odoo.com/forum/help-1

---

CONTRIBUTING.md

We have pull requests open for more than a year and no activity on them.
Grace period:
* 2 months : 2 votes (@moylop260, @elicoidal)
* 3 months : 2.5 votes (@nhomar, @dreispt, @clonedagain)
* 6 months : 4.5 votes (@gurneyalex, @bealdav, @max3903, @gdgellatly, @clonedagain)
* 1 year : 1 vote (@rvalyi)

[IMP] Propose to close unanswered PR after 6 months

---

CONTRIBUTING.md

More info here: 
https://github.com/odoo/odoo/pull/8527

[REF] contributing: api.one deprecated

---

tools/tx_pull.py

Fine-tuning the delay to work around Transifex limitations.
Script made its first and complete automatic run yesterday with this setting:
https://github.com/oca-transbot

[IMP] tx_pull.py: Fine-tuning delays

---

tools/tx_pull.py

Because that file is not being used and make bigger the commits from Transifex

[IMP] tx_pull: Discard en.po file

---

setup.cfg
tools/clone_everything.py
tools/gen_all_addons_tables.py

Includes #41 
This script is intended to be run by the OCA bot.

[ADD] oca-gen-all-addons-tables

---

CONTRIBUTING.md

I think this is necessary to point out how to define installation hooks methods and also having a separated file for them
The feedback is welcomed on this one

[WIP] Add a section for installation hooks to define its use in contributing

---

CONTRIBUTING.md

Reverts OCA/maintainer-tools#164
I merged by mistake.

Revert "[WIP] Add a section for installation hooks to define its use in contributing"

---

CONTRIBUTING.md

- Improve wording and grammar
- Improve some markdown formatting
- Limit line length to 80 characters where possible

Improve language and formatting of OCA Guidelines

---

tools/oca_projects.py
tools/repos_with_ids.txt

Add connector-salesforce and vertical-education repositories

[IMP] Add connector-salesforce and vertical-education repositories

---

tools/oca_projects.py
tools/repos_with_ids.txt

[IMP] Add l10n-indonesia

---

CONTRIBUTING.md

This is to avoid confusions like mine in https://github.com/OCA/product-attribute/pull/112#issuecomment-184280021.

Improve module naming docs.

---

template/module/__init__.py
template/module/__openerp__.py
template/module/hooks.py

Another :gift: for the template.

Add hooks to the module template.

---

template/module/README.rst

Based on suggestion in https://github.com/OCA/event/pull/40#discussion_r56271645 from @elicoidal

Use autonumerated lists for instruction items.

---

CONTRIBUTING.md

The previous domain is expired, update with an address which is still accessible

update the website adresse

---

requirements.txt
setup.cfg
setup.py
tools/bdist_all_wheels.py

**WIP - do not merge** 
I'm creating this PR to show what I'm aiming at.
This trivial scripts creates wheel [1] packages for all odoo addons it discovers in subdirectories. In a nutshell, it does `python setup.py bdist_wheel` recursively and nothing else.
It is built on the foundation laid out in [2][3].
Typical use (pseudo code):
```
virtualenv .
. bin/activate
pip install maintainer-tools
pip install setuptools-odoo
pip install wheel
oca-clone-everything
oca-bdist-all-wheels --dist-dir ~/wheelhouse
```
Then you can install addons with (pseudo code):
```
virtualenv .
. bin/activate
pip install setuptools-odoo
pip install odoo-addon-<addon-name> --find-links=~/wheelhouse
odoo-server-autodiscover
```
What's next?
And then we can think about creating https://wheelhouse.odoo-community.org. …

[ADD] oca-bdist-all-wheels

---

CONTRIBUTING.md

[FIX] typo

---

tools/bdist_all_wheels.py

This bug had the nasty side effect of doing some crossover between
the 8.0 and 9.0 wheels on wheelhouse.odoo-community.org :(

[FIX] bdist_all_wheels: clean more aggressively between runs

---

template/module/static/src/js/module_name.tour.js
template/module/tests/test_something.py
template/module/views/assets.xml

- 9
- template
v9 introduces a completely new module system, and v9 tours get much improved.
Here is a sample tour file that also serves as a sample v9 module. Let's see if now we see more phantomjs tests.
@Tecnativa

[IMP] Template for v9 js module.

---

template/module/__init__.py
template/module/__openerp__.py
template/module/hooks.py

- [post_load info from odoo/odoo](https://github.com/odoo/odoo/blob/2779d463e80eaf903e789c29991a1faef8d07445/openerp/modules/module.py#L317-L322)

[REF] template-module: Add post_load hook

---

CONTRIBUTING.md

You can't use a function before that it's defined

[FIX] CONTRIBUTING.md: Model attibute order.

---

CONTRIBUTING.md

- >=8.0
- (guidelines)
- Add a valid commit way

[REF] never-commit guideline: Add a valid commit

---

CONTRIBUTING.md

[IMP] Include tests folders in CONTRIBUTING.md

---

CONTRIBUTING.md

Fix tests directory guideline, following discussion on #201

Odoo guideline is a tests direcory for py and yml

---

template/module/static/src/js/module_name.tour.js

Fix module indentation, add new hints, add undocumented onload method... Some polish.

Some new hints, fix ESLint errors, add onload().

---

requirements.txt
tools/bdist_all_wheels.py

This is already running on https://wheelhouse.odoo-community.org/oca

support for new style setuptools-odoo package names (setuptools-odoo 1.0.0b7)

---

tools/bdist_all_wheels.py

Send wheel to the wheelhouse only if that version has not been built previously.

build wheels only if they don't exist in wheelhouse

---

CONTRIBUTING.md

external_dependency in tests files must not be protected

---

CONTRIBUTING.md

Create a dedicated chapter for model including naming conventions

---

CONTRIBUTING.md

IMP precision of using Requirement.txt

---

template/module/README.rst

To include in the template the possibility of adding funders of the module

[IMP] template: Include funders

---

tools/tx_pull.py

I think that this piece of code is for faster debug but not for production case.
Is right @pedrobaeza?
Could you share us the production code?

[REF] tx_pull: Remove "date_range" filter

---

tools/repos_with_ids.txt

FIX delivery-carrier repo name

---

CONTRIBUTING.md

Based on @Yajo comment: https://github.com/OCA/web/pull/506#pullrequestreview-14301433
And odoo comments and code: https://github.com/odoo/odoo/blob/fc2e80cb4bc/odoo/sql_db.py#L384-L391
For merger: Squash and merge

[REF] CONTRIBUTING: Remove commit for with registry

---

template/module/README.rst

Minor fix of the wording as proposed in https://github.com/OCA/server-tools/pull/642#discussion_r94187646 - been meaning to submit this for a while, but the comment was the final straw 😛

[IMP] Bug tracker wording in ReadMe

---

README.md

[FIX] Typo in oca-clone-everything instructions

---

CONTRIBUTING.md

See OCA/maintainer-quality-tools/pull/435

[add] mention that coverage ignores *_example modules

---

requirements.txt
setup.cfg
tools/pypi_upload_wheels.py

A thin wrapper around twine, with a local cache of what has already been uploaded.

pypi upload script, with caching

---

tools/pypi_upload_wheels.py

- sometimes the pypi registration process fails, so we retry twice before dying.
- cache registration status

improvement to pypi registration

---

template/module/README.rst

[ADD] discourage private mails to contributors

---

template/module/README.rst
tests/test_repo/__unported__/module3/README.rst
tests/test_repo/module1/README.rst
tests/test_repo/module2/README.rst

- 
- 
- More consistent license link inbetween files. Resolves https://github.com/OCA/maintainer-tools/issues/278

Update license link

---

CONTRIBUTING.md

Add note that Runbot SSH requires commit authorship

[IMP] Contributing: Add note SSH requires authorship

---

CONTRIBUTING.md

From OCA/pylint-odoo#149.
- 8.0
- 9.0
- 10.0
- None
- CONTRIBUTING.md

[ADD] contributing: Add deprecated <tree> attributes guidelines

---

tools/repos_with_ids.txt

[ADD] Apps store repo

---

tools/oca_projects.py

[ADD] Added Apps Store

---

setup.cfg
tools/migrate_branch_empty.py

It also includes an adaptation to version 11.0 for migrate_branch.

migrate_branch_empty: New script for migrating empty branches

---

CONTRIBUTING.md

From https://github.com/OCA/pylint-odoo/pull/157#issuecomment-330388401
- 10.0+
- None
- CONTRIBUTING.md

[ADD] contributing: Add deprecated QWeb directives guidelines

---

tools/copy_maintainers.py

* OCA Contributors
* OCA Members
These teams are not linked to an OCA projet, but having them will gives some
visibility to the members and contributors of the association.
- 
- 
-

tools/copy_maintainers.py: handle two virtual teams

---

CONTRIBUTING.md

Obeying @moylop260 at https://odoo-community.org/groups/contributors-15/contributors-64878 😄 
@Tecnativa

[IMP] Remove utf-8 headers on Odoo >= 11.0

---

CONTRIBUTING.md

Add requirements.txt in chapter for External Dependencies

---

tools/gen_all_addons_tables.py

As installed on the OCA server.

gen_all_addons_tables 11.0

---

template/module/README.rst

License badge is spelled wrong

[FIX] License Badge Spelling in ReadMe

---

template/module/README.rst

Fix Issue #286: svg files not rendered in apps

---

.gitignore

Personally I don't use Eclipse for Odoo, but I have seen some people using it.

[ADD] gitignore: eclipse .settings

---

.gitignore

[ADD] gitignore Visual Studio .vs/

---

.gitignore

I have seen some people using it.

[ADD] gitignore: mac .DS_Store

---

CONTRIBUTING.md

- all
- all
- conventions update

[ADD] a word about migrations

---

tools/oca_projects.py
tools/repos_with_ids.txt

Add currency

---

tools/ocb-sync.sh

@StefanRijnhart @gurneyalex I installed this on the OCA server. 
Your comments are welcome.

Build nightly sdist for OCB

---

tools/oca_projects.py
tools/repos_with_ids.txt

add data-protection

---

tools/gen_addon_readme.py

Similar to the `runbot | Try me` badge.

Add 'Translate me' badge in readme

---

tools/gen_addon_readme.template

readme generator: add issue creation link

---

tools/oca_projects.py
tools/repos_with_ids.txt

add repo 'iot'

---

CONTRIBUTING.md

See example https://github.com/OCA/server-tools/pull/1340
Continuation from https://github.com/OCA/maintainer-tools/pull/196
Reduce the risks about issues related like: https://github.com/OCA/server-tools/issues/1335

[REF] CONTRIBUTING: Consider post_load for monkey patches

---

tools/repos_with_ids.txt

Related: https://github.com/OCA/maintainer-tools/pull/372

Add several repos without runbot id

---

template/module/__manifest__.py

Add links for development_status and maintainers keys

---

setup.py
tools/clone_everything.py
tools/migrate_branch.py
tools/migrate_branch_empty.py
tools/oca_projects.py
tools/set_repo_labels.py

Adapt create_branches* + other script to github3.py >= 1

---

tools/copy_maintainers.py

the values of privacy visibility have changed

update copy maintainers for v11

---

tools/github_login.py
tools/odoo_login.py

Read Odoo login settings from environment, to facilate life of oca-github-bot which is deployed in containers.

Improve Odoo login method

---

tools/gen_addon_icon.py

[IMP] robustify gen-addon-icon

---

setup.py

See # https://github.com/OCA/maintainer-tools/issues/423

pin docutils version

---

tools/gen_addon_readme.py

Fixes https://github.com/OCA/maintainer-tools/issues/426.
@hbrunn @sbidoul

[FIX] 'preloadable = False' should not generate html readme

---

tools/gen_addon_readme.py
tools/gen_addon_readme.template

We have some lowercase `development_status` in the wild, so accept them here.

case-insensitive handling of development_status

---

template/module/controllers/main.py
template/module/data/model_name_data.xml
template/module/demo/model_name_demo.xml
template/module/exceptions.py
template/module/hooks.py
template/module/models/abstract_something.py
template/module/models/model_name.py
template/module/report/report_name.py
template/module/security/some_model_security.xml
template/module/static/description/index.html
template/module/templates/assets.xml
template/module/tests/test_abstract_something.py
template/module/tests/test_something.py
template/module/views/model_name_view.xml
template/module/views/report_name.xml
template/module/wizards/wizard_model.py
template/module/wizards/wizard_model_view.xml

- 10.0 +
- Change tag,name,weblink from openerp to odoo
- Remove data tag from xml files
- Add _description attribute in report_name.py and wizard_model.py

[IMP] Change tag,name,weblink from openerp to odoo

---

template/module/README.rst

Update modulte template README w/ towncrier info

---

README.md

[skip-ci] Use "new" repo path in README

---

setup.py
tools/create_migration_issue.py
tools/migrate_branch.py
tools/migrate_branch_empty.py

This is what I used to create the migration issues for 14.0.
Extracted from @pedrobaeza 's `oca-migrate-branch` and `oca-migrate-branch-empty`.

Add oca-create-migration-issue

---

.travis.yml
setup.py
tox.ini

Require python 3.6+

---

tools/copy_maintainers.py
tools/odoo_login.py

Improve oca-copy-maintainers
Sync the version which is actually being run with the repository
* update the code to use github3 >= 1
* python3 fixes
* manage a blacklist of people who do not want to be invited to the global OCA team

Imp copy maintainers

---

template/module/tests/test_something.py

This specific part of odoo changes a bit depending on your Odoo version.
Reflecting it in the template will help when developing a new addon.
cc @chienandalu

[IMP] Version-specific website tour code samples

---

setup.py

- 
- 
- Fix typo in license argument

Fix license identifier

---

tools/set_repo_labels.py

Following up on https://github.com/OCA/oca-addons-repo-template/pull/63#issuecomment-887637020, and also adding label descriptions
_NOTE: Sort of did it blindly without testing as I'm not maintainer to the repos_

[IMP] oca-set-repo-labels: add new labels and allow to set descriptions

---

setup.py
tools/configure_travis.py

For now, set 3 variables required by https://github.com/OCA/maintainer-quality-tools/pull/556

add: tool to configure travis for an OCA repo

---

.flake8
.github/workflows/ci.yml
.pre-commit-config.yaml
setup.py
tests/test_towncrier.py
tools/oca_towncrier.py
tools/towncrier-template.rst
tox.ini

There was a regression due to a behaviour change
in latest towncrier versions. Also, simplify, by using
the new (?) towncrier --config option.

Fix towncrier missing title underline

---

tools/oca_projects.py

[FIX] Real Estate project

---

tools/repos_with_ids.txt

@simahawk Missed this one for gen-addon-readme

[IMP] runbot_with_ids.txt: Fix typo for realestate

---

tools/set_repo_labels.py

Fix set repo labels

---

tests/data/readme_tests/addon1/README.expected-oca
tests/data/readme_tests/addon_one_maintainer/README.expected-oca
tests/data/readme_tests/addon_two_maintainers/README.expected-oca
tools/gen_addon_readme.py

[IMP] gen_addon_readme: Don't rely anymore on runbot id/generate runboat link

---

tests/data/readme_tests/addon1/README.expected-acme
tests/data/readme_tests/addon1/README.expected-oca
tests/data/readme_tests/addon_one_maintainer/README.expected-acme
tests/data/readme_tests/addon_one_maintainer/README.expected-oca
tests/data/readme_tests/addon_two_maintainers/README.expected-acme
tests/data/readme_tests/addon_two_maintainers/README.expected-oca
tests/test_repo/__unported__/module3/README.rst
tests/test_repo/module1/README.rst
tests/test_repo/module2/README.rst
tools/gen_addon_readme.template

[FIX] gen_addon_readme.template: language typo in readme

---

template/module/readme/CONTEXT.rst
tools/gen_addon_readme.py
tools/gen_addon_readme.rst.jinja

Add a CONTEXT fragment to the readme generator

---

tools/ocb-sync.sh

Remove 12.0 and 13.0, and add 17.0
@Tecnativa

Switch OCB branches to sync for 17.0

---

tools/gen_addon_readme.py

https://github.com/OCA/maintainer-tools/issues/595

[IMP] oca-gen-addon-readme: stop emitting an XML declaration

---

.pre-commit-hooks.yaml

Add a hook for oca-gen-metapackage to use from pre-commit

---

README.md
tools/github_login.py

[FIX] github_login: token only Github auth

---

.pre-commit-config.yaml
setup.py
tests/test_fix_manifest_website.py
tests/test_gen_addon_icon.py
tests/test_gen_addon_readme.py
tests/test_hash.py
tests/test_manifest.py
tests/test_towncrier.py
tests/test_update_pre_commit_excluded_addons.py
tools/add-badges.py
tools/clone_everything.py
tools/configure_travis.py
tools/copier_update.py
tools/copy_maintainers.py
tools/create_branch.py
tools/create_migration_issue.py
tools/fix_manifest_website.py
tools/gen_addon_icon.py
tools/gen_addon_readme.py
tools/gen_addons_table.py
tools/gen_metapackage.py
tools/github_login.py
tools/migrate_branch.py
tools/migrate_branch_empty.py
tools/oca_projects.py
tools/oca_sync_users.py
tools/odoo_login.py
tools/publish_modules.py
tools/set_repo_labels.py

flake8 was failing (probably due to a python version change) so I update pre-commit to use ruff

Add basic ruff config

---

template/module/README.rst

ref https://github.com/OCA/pos/pull/1278#issuecomment-2626629987
CC : @hbrunn

[DOC] mention missing context.rst file
