- template/module/README.rst
This little change avoid HTTPS broken pages in Odoo when user goes to addon details view
> Load OCA image via HTTPS

- CONTRIBUTING.md
The path to go from v8 to v9 is soft with this rule: 
- only import change
- inside use of UserError of the same for both
> fix-exception UserError not in v8

- CONTRIBUTING.md
I think the proposed lambda should call the default method, not return it.
> Fix guidelines for lambda default

- CONTRIBUTING.md
I saw in oca guidelines this matter:
******************
*  **use camelcase for model variable**
* use underscore lowercase notation for common variable.
* since new API works with record or recordset instead of id list, don't suffix
variable name with `_id` or `_ids` if they do not contain an id or a list of
ids.
```python
ResPartner = self.env['res.partner']
partners = ResPartner.browse(ids)
partner_id = partners[0].id
```
******************
I want comment a problem with this:
1. Use CamelCase in a variable don't is a pep8 standard.
1. We will have potential problem of redefined variable.
1. By example:
```python
class ResPartner(model.Models):
...
ResPartner = self.env['res.partner']
```
Why don't use as pep8 told us: snake_case to variable name?
> Variable name CamelCase potential problem of `redefined` variable.

- CONTRIBUTING.md
If we use `external_dependencies` we will have validation of installed packages in install module button.
How to work `external_dependencies` (without `static` folder): [here](https://asciinema.org/a/23098)
But if we don't use `try-except` we will have a error if exists `static` folder:
How to work `external_dependencies` (with `static` folder): [here](https://asciinema.org/a/23103)
Then we will need to add a try-except, but this should be a info error because the real error will show when you want to install the module if you don't use this module then you don't have warning or error just info log.
> [REF] CONTRIBUTING.md: Add external dependencies case.

- CONTRIBUTING.md
Rationale:
It is unfortunate that most modules don't include in the manifest the information of the major Odoo version they target. This is an important information since most of the time modules are incompatible with other Odoo version other than the one they target.
For example: it is frequent to find code in Github with an Odoo module in a "master" branch, but can't be sure of what Odoo version it targets by looking at it's manifest file.
This is so because in the past Odoo/Openerp automatically added the major version to module versions. Thus if your module was version "6.1.1", it would be displayed as "6.1.6.1.1".
It is no longer the case: [now](https://github.com/odoo/odoo/blob/8.0/openerp/modules/module.py#L368) Odoo does not do that if the major version is already appended to the …
> Add guideline for version numbers

- CONTRIBUTING.md
By default new api use name of field in label string.
Use this feature if is posible.
> [REF] CONTRIBUTING: Add use of default label string in fields.

- CONTRIBUTING.md
Reopening #90.
Currently there is consensus in the Odoo version prefix, eg `8.0`
Regarding the next version number we had several views. Current proposal text is for semantic `breaking.feature.fix`.
> Add module version numbers guideline

- template/module/README.rst
As discussed [here](https://github.com/OCA/e-commerce/pull/50#discussion-diff-37542460)
By using a different decoration style from the other sections, the module title gets a more important heading than the other sections when rendered, as it should be.
Reference: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#sections
> Rather than imposing a fixed number and order of section title adornment styles, the order enforced will be the order as encountered. The first style encountered will be an outermost title (like HTML H1), the second style will be a subtitle, the third will be a subsubtitle, and so on.
For example if converting to latex with `rst2latex`, with this correction the module title is put inside the `\title` element and the other sections in a `\section` …
> README template: make the module title a real title

- CONTRIBUTING.md
This PR add next guidelines:
- Avoid use current module in `<record id="current_module.view_id"`.
- Redudant case. You don't need add `current_module.`
- For records of model `ir.filters` use explicit `user_id` field.
- More info [here](https://github.com/odoo/odoo/pull/8218)
- Fix typo
> [REF] CONTRIBUTING.md: Avoid use current module in xml_id and require add user_id in ir.filters

- CONTRIBUTING.md
There was a conflict between these two rules when importing a third party lib due to the `try-except` with the `logger`:
**Rule 1:**
> The imports are ordered as
> 1. Externals libs (One per line sorted and splitted in python stdlib)
> 2. Imports of `openerp`
> 3. Imports from Odoo modules (rarely, and only if necessary)
> 4. Local imports in the relative form
> Inside these 4 groups, the imported lines are alphabetically sorted.
**Rule 2:** 
> In python files where you use a `import external_dependency_python_N` you will need to add a `try-except` with a debug log.
> ```python
try:
import external_dependency_python_N
except ImportError:
_logger.debug('Can not `import external_dependency_python_N`.')
```
> Fixed contributing import rules conflict

- CONTRIBUTING.md
As far I know, OCA decided to stick to python standard (a real good thing).
In coding matter, we should allowed to add this string too.
In the official doc https://www.python.org/dev/peps/pep-0263 § Defining the Encoding, 
it's the first example (and the shorter) that we could use.
@moylop260 asked me to make this PR 
https://github.com/OCA/server-tools/pull/171#discussion_r38918913
I know, somebody will tell us: all oca modules use -\*-  ...  -\*-
But last year, classes in OCA were not in camel case and we changed 
to stick standards and get it easier to read.
And to conclude it's good thing for the earth, you save bytes in the cloud :earth_africa: ;-)
> [IMP] complete coding message

- setup.cfg
- tests/__init__.py
- tests/test_gen_addons_table.py
- tests/test_repo/README.md
- tests/test_repo/README.md.expected
- tests/test_repo/__unported__/module3/README.rst
- tests/test_repo/__unported__/module3/__init__.py
- tests/test_repo/__unported__/module3/__openerp__.py
- tests/test_repo/module1/README.rst
- tests/test_repo/module1/__init__.py
- tests/test_repo/module1/__openerp__.py
- tests/test_repo/module2/README.rst
- tests/test_repo/module2/__init__.py
- tests/test_repo/module2/__openerp__.py
- tools/gen_addons_table
- tools/gen_addons_table.py
A script that replaces a placeholder in the repository-level README.md with two tables showing the available and unported modules along with their version number and a summary (or name if summary is absent). The placeholder is preserved after running the script.
The placeholder in README.md must be like this (```...``` can be anything):
```
[//]: # (addons)
...
[//]: # (end addons)
```
The syntax for markdown comments comes from http://stackoverflow.com/questions/4823468/store-comments-in-markdown-syntax.
Supersedes https://github.com/OCA/maintainer-quality-tools/pull/239, same code, better repo.
> [ADD] gen_addons_table script

- requirements.txt
- setup.cfg
- tools/migrate_branch.py
- tools/oca_projects.py
This script helps to create a new branch for a new Odoo version from the
another existing branch, making the needed changes on contents.
Installation
============
For using this utility, you need to install these dependencies:
* github3.py library for handling Github calls. To install it, use:
`sudo pip install github3.py`.
Configuration
=============
You must have a file called oca.cfg on the same folder of the script for
storing credentials parameters. You can generate an skeleton config running
this script for a first time.
Usage
=====
```
oca-migrate-branch [-h] [-p PROJECTS [PROJECTS ...]] [-e EMAIL]
[-t TARGET_ORG]
source target
positional arguments:
source                Source branch (existing)
target                Target branch (to create)
optional arguments:
-h, --help …
```
> [ADD] migrate_branch: Tool for migrating branches for Odoo versions

- template/module/README.rst
I suggest to indicate the branch in feedback url as following, having a version in template says to me (IMHO) that is the module version as pointed out in CONTRIBUTING.md in [L25](https://github.com/OCA/maintainer-tools/blame/master/CONTRIBUTING.md#L25) with semantical way. But in fact is the branch that the module actually is.
**Current template:**
```text
{project_repo}/issues/new?body=module:%20
{module_name}%0Aversion:%20
{version}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
```
**Proposal template:**
```text
{project_repo}/issues/new?body=module:%20
{module_name}%0Aversion:%20
{branch}%0A%0A**Steps%20to%20reproduce**%0A-%20...%0A%0A**Current%20behavior**%0A%0A**Expected%20behavior**>`_.
```
> Change version to branch

- tools/oca_projects.py
get_repositories() was not filtering out non-addons repositories as intended
> [FIX] typo in oca_projects.py

- tools/clone_everything.py
This is a prerequisite to fully automating the oca-gen-addons-table runs.
> [IMP] add --remove-old-repos options to oca-clone-everything

- template/module/tests/test_something.py
This is because `TransactionCase.setUp()` is expected to return nothing.
> [IMP] Simplify sample case `setUp()`.

- .gitignore
Based on OCA/rma#69 it is needed to add an exception rule for `lib/` folder under `static/` following [guidelines](https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#directories) to allow keep track external libs added to modules, currently it is required to do a `git add -f lib/SpecialLib.js` to get accomplished file inclusion into the repository.
The following asciinema shows this rule https://asciinema.org/a/2ucpz7oua8i6tuyey1cd2plrl
> [WIP][FIX] gitignore: add rule exception for static/lib/

- CONTRIBUTING.md
This comes back every now and then, and up to now it's only common decency that makes most people not do it. I would like to point to some text during review in such cases.
> [ADD] explicitly state that corporate branding is unwanted in OCA modules

- CONTRIBUTING.md
Important section extracted from: [odoo/coding_guidelines_framework](https://doc.odoo.com/contribute/15_guidelines/coding_guidelines_framework/#no-sql-injections-please)
> [REF] CONTRIBUTING.md: Add no-sql-injection

- CONTRIBUTING.md
Important section extracted from: [odoo/coding_guidelines_framework](https://doc.odoo.com/contribute/15_guidelines/coding_guidelines_framework.html#do-not-bypass-the-orm)
> [REF] CONTRIBUTING.md: Add section for "don't bypass the ORM"

- template/module/__init__.py
- template/module/__openerp__.py
- template/module/controllers/__init__.py
- template/module/controllers/main.py
- template/module/data/model_name_data.xml
- template/module/demo/model_name_demo.xml
- template/module/exceptions.py
- template/module/migrations/8.0.1.0.0/post-migrate.py
- template/module/migrations/8.0.1.0.0/pre-migrate.py
- template/module/models/__init__.py
- template/module/models/model_name.py
- template/module/report/__init__.py
- template/module/report/report_name.py
- template/module/security/some_model_security.xml
- template/module/static/src/css/module_name.css
- template/module/static/src/js/module_name.js
- template/module/static/src/xml/module_name.xml
- template/module/tests/__init__.py
- template/module/tests/test_something.py
- template/module/views/assets.xml
- template/module/views/model_name_view.xml
- template/module/views/report_name.xml
- template/module/wizards/__init__.py
- template/module/wizards/wizard_model.py
- template/module/wizards/wizard_model_view.xml
In JS and CSS files, we save a line, in all others we save 5 chars.
> Reduce license headers a bit more.

- template/module/__init__.py
- template/module/__openerp__.py
- template/module/controllers/__init__.py
- template/module/controllers/main.py
- template/module/data/model_name_data.xml
- template/module/demo/model_name_demo.xml
- template/module/exceptions.py
- template/module/hooks.py
- template/module/migrations/8.0.1.0.0/post-migrate.py
- template/module/migrations/8.0.1.0.0/pre-migrate.py
- template/module/models/__init__.py
- template/module/models/model_name.py
- template/module/report/__init__.py
- template/module/report/report_name.py
- template/module/security/some_model_security.xml
- template/module/static/src/css/module_name.css
- template/module/static/src/js/module_name.js
- template/module/static/src/js/module_name.tour.js
- template/module/static/src/xml/module_name.xml
- template/module/tests/__init__.py
- template/module/tests/test_something.py
- template/module/views/assets.xml
- template/module/views/model_name_view.xml
- template/module/views/report_name.xml
- template/module/wizards/__init__.py
- template/module/wizards/wizard_model.py
- template/module/wizards/wizard_model_view.xml
In http://www.gnu.org/licenses/gpl-howto.html I read the sentence
Always use the English word “Copyright”; by international convention,
this is used worldwide, even for material in other languages. The
copyright symbol “©” can be included if you wish (and your character set
supports it), but it's not necessary. There is no legal significance to
using the three-character sequence “(C)”, although it does no harm.
I think that means that the exact word "Copyright" is always necessary,
while the symbol is an optional addition.
> spell Copyright instead of symbol

- CONTRIBUTING.md
Inspired by `computed fields` from [odoo-documentation](https://www.odoo.com/documentation/8.0/reference/orm.html)
> [REF] CONTRIBUTING: Add the inverse method pattern

- template/module/static/src/js/module_name.js
- template/module/static/src/js/module_name.tour.js
- any
- module template
Odoo automatically minifies and concatenates all scripts. Given [`use strict` may only be used at the beginning of a script or of a function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode), minified version would not be strict unless it is declared inside the function. Even worse, a strict script loaded as the 1st one could affect other non-strict ones loaded later.
So, in short, this should be considered a guideline.
@Tecnativa
> [FIX] `use strict` inside functions.

- CONTRIBUTING.md
**New guideline to avoid use `position=replace`**
Use of `<... position="replace">` is not recommended because
could show the error `Element ... cannot be located in parent view`
from other views inheriting with this field.
if you need use this option, must have an explicit comment
explaining why they are absolutely necessary and use a
high value of priority to avoid the error.
```xml
<record id="view_id" model="ir.ui.view">
<field name="name">view.name</field>
<field name="model">object_name</field>
<field name="priority">110</field> 
<field name="arch" type="xml">
<xpath expr="//field[@name='my_field_1']" position="replace"/>
</field>
</record>
```
> [REF] CONTRIBUTING: Use replace is not recommended

- CONTRIBUTING.md
- 
v9
- 
Contributing.mg
- 
This adds a note about avoiding api.v7 except in certain scenarios. Wasn't sure where else it fit, so I put it in idioms.
Admittedly I could be completely off-base here, but this seems like a wise recommendation?
> [ADD] contributing: Add note about avoiding api.v7

- .travis.yml
Fix current build stable travis error of flake8 v3.0.2
Freezing v2.6.2 working fine!
Issue: https://gitlab.com/pycqa/flake8/issues/201
> [FIX] flake8 runtime PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

- CONTRIBUTING.md
- master
- CONTRIBUTING.md
This PR adds a (much needed IMO) Table of Contents to our contributing guidelines.
Unfortunately no auto TOC is supported by GitHub, so I generated using https://github.com/ekalinin/github-markdown-toc . Everyone should go give a thumb to [this Github issue](https://github.com/github/markup/issues/904) as well even though they probably won't pay attention.
> [ADD] contributing: Add TOC

- CONTRIBUTING.md
- template/module/examples/README.rst
Many times we need add `examples` files.
- They are used like as reference or they are used to process out of manifest file.
A example is the following file:
- https://github.com/OCA/l10n-switzerland/blob/8.0/l10n_ch_account_statement_base_import/data/UBS_export.csv
Inspired by https://github.com/OCA/pylint-odoo/issues/47#issue-164800453
> [REF] template: Consider 'examples' folder

- template/module/tests/test_something.py
- 9.0
- Http test case for backend
* `module` is the argument to define a module to test in backend, not `mod` in v9 - not sure about other versions
> [FIX] test_something: Fix phantom string for backend

- tools/gen_addons_table.py
- tools/migrate_branch.py
[RFR] Check \_\_manifest\_\_.py when generating addons tables
and migrating branches
[IMP] Rename manifest to \_\_manifest\_\_.py for 10.0 branches
[FIX] Fetch the tree of the target branch, not of the project main branch
[IMP] Fix missing comma when adding dictionary entry
[IMP] Sort modules by name on the migration issue
[ADD] Delete setup addon directories on branch migration
> Changes in order to push 10.0 branches to OCA projects

- CONTRIBUTING.md
@simahawk and me purpose to allow spliting controllers/main.py in several files when there are many controller methods or when big ones. And this case can be often in website modules.
We've discussed this in OCA Sprint in Brussels. Now this is our proposal and maybe @lasley, @pedrobaeza, @dreispt and @gurneyalex have something to say about this.
> Allow to split main.py in severeal files

- tools/gen_addons_table.py
When addon descriptions contain unicode characters oca-gen-addons-table would fail.
> [FIX] properly handle unicode in oca-gen-addons-table

- template/module/static/src/js/module_name.js
- template/module/static/src/js/web_module_name.js
- template/module/static/src/js/web_module_name.tour.js
- template/module/static/src/js/website_module_name.js
- 
v9
- 
template
- Upgrade JS to new API
- Upgrade onload method to use core bus web_client_ready
- Add an exported method
REF https://github.com/OCA/web/pull/386#discussion_r72024916
cc @antespi @pedrobaeza
> [MIG][9.0] template: Upgrade JS API

- template/module/static/tests/js/module_name.js
- template/module/templates/assets.xml
- 9.0
- Template
- Adds an example for QUnit test suite injection via QWeb
- Adds PhantomJS test example
> [ADD] template: PhantomJS Test Sample

- CONTRIBUTING.md
Currently if we have many external dependencies we are using:
```python
try:
import M2Crypto
except ImportError:
_logger.debug('Can not import M2Crypto.')
try:
from OpenSSL import crypto
except ImportError:
_logger.debug('Can not import OpenSSL.')
```
But we could use a reduced way:
```python
try:
import M2Crypto
from OpenSSL import crypto
except ImportError as err:
_logger.debug(err)
```
Currently we have a logger debug just of external dependencies of python libraries but we don't have a logger debug for external dependencies of binaries, using the same reduced way:
```python
try:
import M2Crypto
from OpenSSL import crypto
DIFF3_BIN = tools.find_in_path('diff3')
except (ImportError, IOError) as err:
_logger.debug(err)
```
> [REF] CONTRIBUTING: Grouping external dependencies exception

- tools/gen_all_addons_tables.py
The default git config was changed on the gitbot server which caused oca-gen-addons-table to fail since a few days. This should fix by being more explicit in the git push command.
> [FIX] make oca-gen-all-addons-table more resilient to git config changes

- tools/tx_pull.py
This improves the wait times for avoiding rate limits using webservices until limit error codes are obtained. 
I have also protected all the possible failures in the process, iterating over a full synchronization on all the OCA projects. With this, there are enough guarantees that a full sync process finishes.
> [IMP] tx_pull: Handle rate limits

- CONTRIBUTING.md
The `pass` into block except is not a good practice!
By including the `pass` we assume that our algorithm can continue to function after the exception occurred
If you really need to use the `pass` consider logging that exception
```python
try:
sentences
except:
pass
_logger.debug('Pass')
```
> [IMP] Adding exception section for good practice

- requirements.txt
- All
- All
- [FIX] Error in requirements.txt with version bzr-2.6.0
```bash
Collecting bzr==2.6.0 (from -r requirements.txt (line 4))
Using cached bzr-2.6.0.tar.gz
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-OeOdUi/bzr/setup.py", line 205, in <module>
pyrex_version_info = tuple(map(int, pyrex_version.rstrip("+").split('.')))
ValueError: invalid literal for int() with base 10: '1post0'
----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-OeOdUi/bzr/
```
> [FIX] maintainer-tools: Fix up in requirements bzr version 2.6 replaced for 2.7

- template/module/tests/test_something.py
This adds `debug=assets` to our HTTP case examples. Ref https://github.com/OCA/maintainer-quality-tools/issues/438#issuecomment-288966049
cc @yajo
> [IMP] Add debug assets to HTTP cases

- tests/test_repo/README.md.expected
- tools/gen_addons_table.py
> addons tables: cope with slight change in github markdown rendering

- tools/bdist_all_wheels.py
classifiers for regular (one addon) packages are added by setuptools-odoo
> add trove classifiers for OCA meta packages

- CONTRIBUTING.md
* Add rule to OCA guidelines requiring all demo record XML IDs to end in `demo`
* Add rule to OCA guidelines requiring all XML IDs for data records to begin with the record's model name
The first portion was suggested [here](https://github.com/OCA/delivery-carrier/pull/122#discussion_r113841148) by @lasley and seems like a good move since it can be difficult to tell demo records apart from normal ones. The second part was then added based on [a discussion in this PR](https://github.com/OCA/maintainer-tools/pull/272#pullrequestreview-37844704).
> [ADD] Demo record XML ID rule

- template/module/__init__.py
- template/module/controllers/__init__.py
- template/module/models/__init__.py
- template/module/report/__init__.py
- template/module/tests/__init__.py
- template/module/wizards/__init__.py
- All
- All
- Do we want to keep copyright into '__init__.py' files? Depending on reviewers, you can be asked to remove/put copyright from 'init' files. A good point that goes in this direction is that it doesn't contains code.
> remove copyright from __init__.py

- template/module/data/model_name_data.xml
- template/module/demo/model_name_demo.xml
- template/module/security/some_model_security.xml
- template/module/views/model_name_view.xml
- template/module/wizards/wizard_model_view.xml
* Update module template to reflect new XML ID rules
* Correct several XML IDs in module template not following older style rules
This PR is connected to the new rules introduced in https://github.com/OCA/maintainer-tools/pull/272
> [FIX] XML IDs in module template

- CONTRIBUTING.md
* Add info to OCA guidelines explaining how to debug test failures that do not show up locally by SSHing into Runbot
> [ADD] Runbot SSH info

- tools/repos_with_ids.txt
Repo 170 - connector-rt doesnot exist in Github
Removed
> Remove phantom repo

- CONTRIBUTING.md
- template/module/README.rst
- template/module/__openerp__.py
I hereby propose a new convention for the website key in the manifest.
The current tradition is to put the author company website or the OCA website. Neither of these provide directly relevant information about the addon. 
I therefore propose to use the link to the OCA github repository which provides direct access to the addon README which in turn provides immediate access to the most relevant information, including detailed authors and contributors information.
> [IMP] new convention for website key

- .travis.yml
In order to fix https://github.com/OCA/maintainer-tools/pull/289#issuecomment-328924874
> [REF] .travis.yml: Use distribution precise linux 12.04

- tools/ocb-sync.sh
this add sync from upstream for odoo 11. Only merge after the saas-18 branch is renamed.
> [ADD] sync for odoo 11

- tools/pypi_upload_wheels.py
- cope with the sunsetting of legacy pypi: https://mail.python.org/pipermail/distutils-sig/2017-June/030766.html
- `twine register` is not supported nor necessary with pypi.org
- use `dumbdbm` instead of `anydbm` for portability
@gurneyalex in addition to this I had to compile a python 2.7.13 on odoo-community.org, because wheezy's 2.7.3 is hopelessly obsolete wrt https support.
> [IMP] various improvements to pypi_upload_wheels

- tools/repos_with_ids.txt
"maintenance" repository (id=240) is missing in [repos_with_ids.txt](https://github.com/OCA/maintainer-tools/blob/master/tools/repos_with_ids.txt)
> [ADD] missing "maintenance" in repos_with_ids.txt

- template/module/tests/test_something.py
* Add `post_install` and `at_install` keys
* Fix PEP
Not including the `post_install` and `at_install` keys can yield random errors, such as missing static QWeb templates.
Cc @hughesbm
> [FIX] UICase Fixes

- CONTRIBUTING.md
- None
- None
- Currently the section _External dependencies_ is under _XML files_ which feels like a non sequitur. I believe it makes more sense to put the section _External dependencies_ under _Modules_.
> [IMP] contributing: restructurize guidelines

- template/module/models/abstract_something.py
- template/module/tests/__init__.py
- template/module/tests/test_abstract_something.py
* Add a sample of a testing strategy for an abstract model
We may want to rename some things, or possibly change the structure, but this is a good one to include IMO. 
This is pulled from @obulkin resolution of OCA/web#490 as inspired by @hbrunn
> [ADD] template: Abstract model test strategy

- tools/oca_projects.py
This repo is not subject to regular rules and in particular must not be published to pypi.
> Ignore oca-custom in oca_projects.py

- tools/set_repo_labels.py
* Add a `migration` label as light purple (#d4c5f9)
Any thoughts? Here's a screenshot of the color:
I don't think I've seen anything conflicting with it in any of the repos, but it's possible.
> [IMP] Add a `migration` label

- requirements.txt
- tools/copy_maintainers.py
- tools/odoo_login.py
At the request of the Board, I changed the script to handle a team for the PSC Representative of the projects. With this version, a team is created (if needed) for the PSC Representative with the proper access, and synchronised with the normal team, and the PSC Representative is added to the team. 
Result:
> oca-copy-maintainers: manage PSC Representative team

- template/module/__openerp__.py
- template/module/demo/assets.xml
- template/module/templates/assets.xml
Usually tests depend on demo data, and they are enabled only in development
environments. By enabling the asset in demo data, you remove them from
production instances and thus increase their performance and security, losing
no features.
This follows what was discussed in https://github.com/OCA/web/pull/402#discussion-diff-74550578.
@Tecnativa @lasley
> Enable test tours only in demo instances.

- tools/gen_addon_readme.template
Without that, it looks weird when DESCRIPTION.rst itself
ends with a bullet list.
> Add Table of contents separator in README template

- tools/copy_maintainers.py
oca-travis is the user used in travis scripts to push back changes to github, it must be a member of the Core Maintainers team.
cc/ @gurneyalex
> add oca-travis to copy-maintainers

- tools/gen_addon_readme.py
As well as auto add missing newline at eof, to avoid
rst syntax errors.
> readme generator: ignore empty fragments

- tools/gen_addon_readme.template
To avoid a duplicate implicit target error (conflicting
with the Maintainers section title) when there is more
than one maintainer.
fixes #364
> [FIX] readme generator: use anymous hyperlink

- tools/main_branch_bot.py
- tools/pypi_upload.py
This makes oca-main-branch-bot python 3 compatible while still being able to run on python 2 branches.
This is necessary to support some 11.0 manifest that have non ascii characters in name or authors, and can be parsed by python 3 and not python2.
> Improve python 3 compatibility

- tools/runbot_ids.py
This is to avoid redeploying maintainer-tools on the oca server for the bot each time a new repo is added.
> [IMP] read runbot ids online

- setup.py
Requiring setuptools<31 now breaks travis builds. This was bound to happen
sooner or later. Allowing the latest setuptools version
has only one drawback: it obliges people using wheels built
with recent versions to always use odoo-autodiscover>=2 on Odoo<11.
This is the safest and easiest anyway and it is best practice
so most people should be unaffected.
> Relax setuptools version constraint.

- tools/gen_addon_readme.py
It is exactly the same as README.rst, but useful nevertheless since
apps.odoo.com gives better visibility to addons with an html description.
Manually generated index.html are preserved.
This incidentally fixes #369
> gen-addon-readme: generate static/description/index.html

- CONTRIBUTING.md
Currently, there is a discrepancy between the documentation and the
module template, regarding how XML files should be named. The
documentation says they should be without suffix
(views/res_partner.xml), but the model template says it should be with
suffix (views/res_partner_view.xml).
To be consistent, this modifies the documentation so it matches the
module template.
Closes #388
> [DOC] Require suffix for XML file names

- tools/set_repo_labels.py
> add "ready to merge" label

- template/module/readme/CONFIGURE.rst
- tools/gen_addon_readme.py
- tools/gen_addon_readme.template
Hi all, 
First, thanks for this great tool.
This PR adds 2 improvements on oca-gen-addon-readme (the second depends on the first).
Commit 1 : make the organization name configurable, to let the possibility to generate readme for incubator / custom repositories. (= non OCA repo)
for that purpose, 
-> add a new argument ``--org-name`` with default value set to ``OCA``
-> replace hard coded 'OCA' by the org_name, in all the URLs
-> hide some parts of the template, if the organization is not OCA
Commit 2 : Fix a recurring trouble on figures. In a few words, relative path of figures are not working in the same time on github, on odoo, and on odoo appstore. So, add a little script to translate relative path into full github path. (using rawcontent).
For the time being, to make the image …
> [IMP] oca-gen-addon-readme : make organization name configurable and fix images URL

- README.md
- All
- All
- update doc
@legalsylvain
> IMP readme for specific use of gen-readme

- tests/test_manifest.py
- tools/main_branch_bot.py
> [IMP] do not fail if setup directory is absent

- tools/gen_addon_readme.py
Problem:
The code it's reading the manifest twice. The second is in the `try` one.
Thus, the first reading of the manifest is useless. Furthermore, you may have an unexpected `NoManifestFound` error in the first reading because the absence of the `try`.
Solution:
Delete the second one and put a `try` in the first.
> [FIX] tools.gen_addon_readme: deduplicate manifest reading

- tools/github_login.py
Fix info URL provided after wrong authentication caused by already existing token.
> [FIX] informative url to already existing tokens during authentication

- README.md
- setup.py
- tests/test_gen_addon_icon.py
- tools/gen_addon_icon.py
To provide an icon for our modules we generate them automatically.
To generate the icon for the module `auth_keycloak`:
$ oca-gen-addon-icon --addon-dir=auth_keycloak
----
My idea is to implement it after in the OCA github bot.
> [ADD] tools: icon generator

- tools/pypi_upload.py
> [FIX] pypi uploader: ensure unicode twine output

- template/module/__manifest__.py
- tools/gen_addon_icon.py
Odoo does things if the module has a static folder. See https://github.com/OCA/OCB/blob/11.0/odoo/http.py#L1340.
Modules with `'preloadable': False` should not have a static folder.
> [ADD] manifest: preloadable flag

- tools/gen_addon_readme.py
- tools/gen_addon_readme.template
The Alpha badge is visible but not enough to get people aware
of the consequences of using Alpha addons.
> Add a warning in readme for Alpha status

- template/module/__manifest__.py
-  11.0+
- Add 'excludes' key in manifest file to avoid conflicts between modules
CC @pedrobaeza
> [ADD] 'excludes' key in manifest file

- tools/gen_addon_readme.py
Trivial patch to
- allow images in table.
- allow shortcut on images. (add ``|shortcut|`` before the image.) 
(the regex doesn't match for the time being)
Note I need it to generate this readme file : 
https://github.com/legalsylvain/stock-logistics-barcode/tree/11.0_ADD_mobile_app_picking/mobile_app_picking
Thanks.
> [FIX] allow images in table, and shortcut usage

- template/module/__init__.py
- template/module/__manifest__.py
- template/module/controllers/__init__.py
- template/module/controllers/main.py
- template/module/exceptions.py
- template/module/hooks.py
- template/module/models/__init__.py
- template/module/models/abstract_something.py
- template/module/models/model_name.py
- template/module/report/__init__.py
- template/module/report/report_name.py
- template/module/tests/__init__.py
- template/module/tests/test_abstract_something.py
- template/module/tests/test_something.py
- template/module/wizards/__init__.py
- template/module/wizards/wizard_model.py
-  11.0 +
- UTF-8 as the default source encoding for Python 3.x.
> [RM] encoding=utf-8 is not needed anymore in Python 3.x+

- .pre-commit-hooks.yaml
- README.md
- tools/gen_addons_table.py
- oca-gen-addons-table now supports setting `--readme` and `--addons-dir` paths, to support non-oca repos structures.
- It also supports a more helpful `--help`, which also suggests you to add [prettier exlusion tags](https://prettier.io/docs/en/ignore.html#markdown), to avoid double-edition of README.md files.
- pre-commit hooks supplied and documented.
@Tecnativa @sbidoul
> Provide pre-commit hooks, compatible with prettier

- tools/copy_maintainers.py
The project names in the OCA database have been changed to allow for a better presentation on the website.
We now need some heuristics to detect the corresponding GitHub teams.
> [FIX] copy_maintainers: detect GitHub teams

- .flake8
- setup.py
- tests/test_towncrier.py
- tools/gitutils.py
- tools/oca_towncrier.py
- tools/towncrier-template.rst
One difficulty of maintaining changelog (`readme/HISTORY.rst` in OCA addons) is merge conflicts on PRs that touch it.
[towncrier](https://github.com/hawkowl/towncrier) is a tool that lets contributors write news fragment files (in `readme/newsfragments/` in OCA addons). News fragments have the issue/pr number as name and a suffix (.feature, .bugfix, .doc, .removal) indicating the type of changelog entry.
When run, `towncrier` generates a commit that updates `HISTORY.rst` in a standardized manner and removes the news fragment files.
This maintainer tool script does this with a configuration that works well with `oca-gen-addon-readme`. A typical commit produced by this tool can be seen [here](https://github.com/OCA/mis-builder/commit/2f87e1a3d0bef7a7cdbe219d706af3a0ca958ad0).
My idea is to …
> [ADD] oca-towncrier

- tests/test_gen_addons_table.py
- tools/gen_addons_table.py
There is a warning foreseen in that case.
Regression was introduced in #436
> gen-addons-table: do not fail if README.md is absent

- setup.py
- tools/config.py
- tools/oca_projects.py
- tools/publish_modules.py
> [IMP] oca_publish_modules: tool for publishing modules

- README.md
Current installation method refers to using virtualenv, but with pipx gaining in popularity we should add pipx install instructions.
> Add pipx method to installation methods

- .pre-commit-hooks.yaml
- setup.py
- tests/test_update_pre_commit_excluded_addons.py
- tools/update_pre_commit_excluded_addons.py
In repos with `installable=False` addons it is useful to exclude these from the pre-commit checks.
This PR provides a pre-commit hook that updates `.pre-commit-config.yaml` with the exclude list, making sure the exclude list remains up-to-date.
Typical usage in https://github.com/OCA/oca-addons-repo-template/pull/3
> [ADD] pre-commit hook to exclude not installable addons

- .pre-commit-hooks.yaml
Before this patch, the hook would not run if an excluded addon (because installable=False) was flipped to installable=True.
> always run oca-update-pre-commit-excluded-addons hook

- .pre-commit-hooks.yaml
- setup.py
- tests/test_fix_manifest_website.py
- tools/fix_manifest_website.py
Setting a wrong website key in manifest is a common error that is currently not reported to contributors.
This `oca-fix-manifest-website` script is intended to be added in a pre-commit hook.
> [ADD] oca-fix-manifest-website

- README.md
- tools/gen_addon_icon.py
- Allows to use a custom icon with `--src-icon` option.
> [IMP] Allow to set a custom icon

- README.md
- 
- 
- Build badge now points to the `CI` Action on GitHub.
>  Fix build badge, it was still pointing to Travis

- setup.py
By following the installation README, I got the case where a pip install (pip 20.1.1) created an egg zip file instead of an egg folder.
So any tools expecting to find an egg folder (with templates inside) just fails.
The `zip_safe=False` parameter force the extraction to an egg folder.
> [FIX] Force egg extraction otherwise templates are not available

- tests/test_repo/README.md.expected
- tests/test_repo/module1/__openerp__.py
- tools/gen_addons_table.py
supersed #505
partial close : #454
Add maintainers column in the readme file of the repository.
The inserted image contains the following code
[![MAINTAINER](https://github.com/MAINTAINER.png?size=30px)](https://github.com/MAINTAINER)
Partial result
See full result : https://github.com/legalsylvain/pos/tree/12.0-TEST-oca-gen-addons-table-maintainers#readme
Thanks for your review.
CC : @sbidoul, rousseldenis
CC : @quentinDupont
> [IMP] add maintainers column in addons table. #454

- tools/github_clabot_hook.py
github_clabot_hook is a tool to configure the clabot hooks on all OCA
repositories.
> [ADD] github_clabot_hook

- setup.py
This was only needed for Python 3.4 and lower.
@moduon MT-83
> [FIX] remove outdated dependency argparse

- tools/copy_maintainers.py
The permission argument is deprecated in the GitHub API and was causing errors.
> copy_maintainers: remove deprecated create_team arg

- .github/workflows/ci.yml
- tools/gen_addon_readme.py
- tox.ini
Python3.11 no longer works with Universal newline in file read mode, as it is used by default from 3.3
- 
- 
- Adapts the oca-gen-addon-readme to work with Python3.11. As you can see in https://docs.python.org/3.11/whatsnew/3.11.html
Universal file read mode flag is no longer supporte as it is the default after python 3.3
> [IMP] adapt to work on Python3.11

- setup.py
- tools/copier_update.py
- tools/github_login.py
- tools/oca_projects.py
This is the script I currently use to update dotfiles. I post it here in draft state case anyone is interested.
Needs thinking:
- This should probably be a bot action
- It runs pre-commit locally. If ok, it pushes to the main branch with [ci skip]. If not it creates a PR ([example](https://github.com/OCA/event/pull/200)). This is a shortcut to save CI build time, but in the general case, a dotfiles update could break something else than pre-commit. So it might be best to always create a PR and immediately ocabot merge it. The drawback is that it will create a ci build storm...
- Also, running pre-commit locally might have security implications
- Yet, it is currently necessary to autoformat copier-generated files (e.g. yaml files)
> [ADD] oca-copier-update

- tools/gen_addon_readme.py
- all
- oca-gen-addon-readme
- Allow to use custom templates passing `--template-filename=/path/to/filename.template` to the **oca-gen-addon-readme** command
MT-303 @moduon @yajo
> [IMP] oca-gen-addon-readme: Allow to use custom templates

- tests/data/readme_tests/addon1/README.expected-acme
- tests/data/readme_tests/addon1/README.expected-oca
- tests/data/readme_tests/addon_one_maintainer/README.expected-acme
- tests/data/readme_tests/addon_one_maintainer/README.expected-oca
- tests/data/readme_tests/addon_two_maintainers/README.expected-acme
- tests/data/readme_tests/addon_two_maintainers/README.expected-oca
- tools/gen_addon_readme.template
- Avoid the fucking trailing whitespace:
> [FIX] gen_addon_readme.template: Avoid trailing whitespace

- tests/data/readme_tests/addon1/README.expected-oca
- tests/data/readme_tests/addon_one_maintainer/README.expected-oca
- tests/data/readme_tests/addon_two_maintainers/README.expected-oca
- tools/gen_addon_readme.py
The other URL is an implementation detail of the current UI.
> gen-addon-readme: use the canonical URL for runboat builds

- setup.py
Since we now have `oca-gen-addon-readme --if-fragment-changed` which we will deploy to the OCA bot and pre-commit we can unpin docutils.
closes #423 
towards #564
> Unpin docutils

- setup.py
- tests/test_gen_metapackage.py
- tests/utils.py
- tools/compat.py
- tools/gen_metapackage.py
This is a port and modernization of the metapackage generation part of [setuptools-odoo-make-default](https://github.com/acsone/setuptools-odoo#id6).
What we mean by metapackage is a package that has all the addons in the repo as dependencies.
We now generate a standard-compliant `pyproject.toml` instead of a `setup.py`.
> Add `oca-gen-metapackage` script to generate `setup/_metapackage/pyproject.toml`

- .pre-commit-hooks.yaml
- setup.py
- tests/test_gen_external_dependencies.py
- tools/gen_external_dependencies.py
This is meant to replace `setuptools-odoo-get-requirements` and is implemented using the standard python build backend interface, and therefore independent of setuptools-odoo.
> Add pre-commit hook to generate external dependencies (`requirements.txt`)

- tests/test_gen_addon_readme.py
- tools/gen_addon_readme.py
Add an option to not change the source digest in the generated file.
Since 
- we want to generate README.rst in pre-commit,
- the manifest is part of the source digest,
- the manifest can change even if PR does not modify the README, 
this option should help avoid merge conflicts.
> gen-addon-readme: add --keep-source-digest

- tools/config.py
- tools/oca_projects.py
This PR tends to fix the issue that 17.0 branch are not taken into account by oca_projects.py get_repositories_and_branches function causing for instance that these are not created in Weblate (see https://odoo-community.org/groups/contributors-15/contributors-1545495).
The script used for populating weblate is calling that function which does not return v17.0 branch (https://github.com/OCA/oca-weblate-deployment/blob/75ad176738d15ac2d99aaf0311e31036e39e74d9/wocg-oca#L12C21-L12C50) 
According to https://github.com/OCA/maintainer-tools/pull/539 MAIN_BRANCHES was deprecated and should not be used anymore, so I remove it from default parameter.
With this change, 17.0 branches are properly returned.
> [FIX] do not use MAIN_BRANCHES anymore

- tools/config.py
The 3 following OCA repos are not addons repos and should be added to the corresponding list so that they are not retrieved by other scripts looking for addons :
- oca.recipe.odoo
- repo-maintainer
- repo-maintainer-conf
> [ADD] oca.recipe.odoo and repo-maintainer* as not addon repos

- setup.py
- tests/test_towncrier.py
- tools/oca_towncrier.py
- tools/towncrier-template.md
If readme fragments uses the _md_ format, generates the history file into the same format
This should fix the issue preventing the merge of some PR as https://github.com/OCA/search-engine/pull/176#issuecomment-1857431949
> [FIX] oca-towncrier: Add support for Mardown format

- tools/clone_everything.py
When cloning for the first time, that is a long process,
the user is not presented with any feedback on the progress.
> [IMP] clone_everything: print cloning progress

- tools/copier_update.py
See individual commits for more information.
> Various improvements to oca-copier-update

- tools/gen_addon_readme.py
- when pandoc is not available in PATH, [`ensure_pandoc_installed`](https://github.com/JessicaTegner/pypandoc/blob/1341920fa1c1ce661a0ac22138ce819eb73d9f77/pypandoc/__init__.py#L821) downloads its installer in current directory and unpacks it
- one might question that intrusive behavior; in our case we can consider it as beginner friendly
- we just need to delete the installer to avoid polluting repos  
fixes #619
> oca-gen-addon-readme: delete pandoc installer

- README.md
- tools/github_login.py
Use `gh auth token` as a third source of GitHub token
> Improve gh login

- tests/test_towncrier.py
- tools/towncrier-template.md
Use of the correct title level when generating the history into md format
This is required to fix https://github.com/OCA/rest-framework/pull/453#issuecomment-2385509745
ping @sbidoul
> oca-towncrier: Use correct title level

- .github/workflows/ci.yml
- 
- 
- Try fixing red CI on  #639 by configuring parallel tests on Coveralls as explained here : https://github.com/coverallsapp/github-action?tab=readme-ov-file#complete-parallel-job-example
> [FIX] parallel Coveralls tests

- tests/test_repo/__unported__/module3/README.rst
- tests/test_repo/module1/README.rst
- tests/test_repo/module2/README.rst
- tools/gen_addon_readme.py
Before this commit, "license" was used in:
- Image's alternative text
- License URL.
While "licence" was only used in the badge's text.
To be consistent, "license" is now used everywhere. We're preferring that form because:
- It's the way licenses are referred to in their actual names and content (e.g. "GNU Affero General Public License").
- License file is called `LICENSE`.
- The Manifest key of Odoo modules is called that way.
- 
- 
-
> gen-addon-readme: consistency between words "license" and "licence"

- .github/workflows/ci.yml
- pyproject.toml
- tox.ini
Add Python 3.13.
Don't use retired Ubuntu 20 runner
Drop support for old Pythons not available in CI.
> Fix CI, drop support for python 3.6 and 3.7

- tests/test_repo/README.md.expected
- tools/gen_addons_table.py
This PR improves how maintainer avatars are rendered in the generated README table.
When a maintainer does not have a custom GitHub avatar, their image appears larger than others. This creates a visual inconsistency that affects readability and aesthetics.
All maintainer avatars are rendered at a fixed size (32x32px) using HTML <img> tags with a border-radius: 50% style to enforce a modern, consistent round shape.
This ensures a cleaner and more polished appearance for the table, regardless of whether the user has a custom avatar or not.
> [IMP] Render all maintainer avatars in same size

- README.md
Otherwise it is shown like this
> Fix relative link to readme structure

- README.md
- Update README.md: After replaced setup.py to pyproject.toml in #648, README.md still shows old setup procedure.
> [IMP] Update installation instructions for clarity and consistency

- tools/gen_addon_readme.py
Following a report from a Windows user on discord.
> [FIX] oca-gen-addon-readme: don't assume index.html encoding
